# Generated by Django 6.0.6 on 2026-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
